//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermutRaterApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VermutRaterApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ES.
        /// </summary>
        internal static string Ca {
            get {
                return ResourceManager.GetString("Ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando vermuts....
        /// </summary>
        internal static string Carregantvermuts {
            get {
                return ResourceManager.GetString("Carregantvermuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por origen o nombre.
        /// </summary>
        internal static string Cercarperorigenonom {
            get {
                return ResourceManager.GetString("Cercarperorigenonom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contrasenya {
            get {
                return ResourceManager.GetString("Contrasenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        internal static string Crearcompte {
            get {
                return ResourceManager.GetString("Crearcompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Aún no tienes cuenta?.
        /// </summary>
        internal static string Encaranotenscompte {
            get {
                return ResourceManager.GetString("Encaranotenscompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe tus notas aquí....
        /// </summary>
        internal static string Escribetusnotasaquí {
            get {
                return ResourceManager.GetString("Escribetusnotasaquí", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por estado.
        /// </summary>
        internal static string Filtrarperestat {
            get {
                return ResourceManager.GetString("Filtrarperestat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string Iniciasessió {
            get {
                return ResourceManager.GetString("Iniciasessió", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce tu correo electrónico.
        /// </summary>
        internal static string Introdueixelteuemail {
            get {
                return ResourceManager.GetString("Introdueixelteuemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string Nomdusuari {
            get {
                return ResourceManager.GetString("Nomdusuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * Solo disponible dentro del radio de 50 m..
        /// </summary>
        internal static string Nomésdisponibledinsdelradide50m {
            get {
                return ResourceManager.GetString("Nomésdisponibledinsdelradide50m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * Solo puedes registrarte cerca de la vermutería..
        /// </summary>
        internal static string Noméspotsregistrarteapropdelavermuteria {
            get {
                return ResourceManager.GetString("Noméspotsregistrarteapropdelavermuteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por.
        /// </summary>
        internal static string Ordenarper {
            get {
                return ResourceManager.GetString("Ordenarper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🎲 Sorpresa.
        /// </summary>
        internal static string Sorpresa {
            get {
                return ResourceManager.GetString("Sorpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Probado!.
        /// </summary>
        internal static string Tastat {
            get {
                return ResourceManager.GetString("Tastat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu voto.
        /// </summary>
        internal static string Tuvoto {
            get {
                return ResourceManager.GetString("Tuvoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vermupedia.
        /// </summary>
        internal static string Vermupedia {
            get {
                return ResourceManager.GetString("Vermupedia", resourceCulture);
            }
        }
    }
}
